 #+TITLE: My experience learning Scheme Theory
#+BIND: org-export-html-auto-postamble nil
#+ATTR_HTML: border="2" rules="all" frame="border" align="center"
#+OPTIONS: toc:nil 
#+OPTIONS: author:nil 
#+OPTIONS: html-postamble:nil
#+OPTIONS: num:nil 
#+OPTIONS: \n
#+OPTIONS: *
#+OPTIONS: toc:nil        (no TOC at all)
#+options: num:nil
#+OPTIONS:   H:2 





When I learned it, I didn't know much coming in (I had taken a course on complex curves, but not schemes). I took a year long scheme theory course my first year from Harthshorne (the person, from his book) in the Fall, and part II in the spring from Paul Vojta. The second semester, I also took a reading course on Silverman's Arithmetic of Elliptic Curves, which is more down to earth and really helped motivate scheme theory (a lot of things just become much cleaner from the scheme theory point of view; example: if you have a variety X over Q (i.e. defined by equations with rational coefficients), and if X is smooth, then the reduction of X mod p is also smooth for all but finitely many primes p [this is very difficult without schemes, and kind of obvious with schemes]). 

Also concurrently I read (in less detail) as many other texts on the subject as I could. An important one is Eisenbud and Harris's "The Geometry of Schemes", which is a companion book rather than a text. But I also read whatever online course notes I could find (William Stein has some from when he was learning), and read little bits of other books like Shaferevich's books and Qing Lui's books. 

Also concurrently I would backtrack a bit and read commutative algebra texts, like Atiyah--Macdonald (short and concise), and Eisenbud's commutative algebra book (huge, but with lots of examples, motivation, etc). 

Then I studied over the summer for my oral qualifying exam on Scheme theory, the following September. That was valuable, and I passed.

Then year 2 I took the scheme theory course again (but put less work into it); Mark Haiman taught it, from EGA. Year 3 I took the first half of the course (from Brian Osserman), but then there was a topics course on stacks in the spring and I decided to stop attending scheme theory every year. Stacks really reinforced what I was learning, as did reading papers and doing research. 

I also ended up reading a lot of Qing Liu's book while working on research projects (Hartshorne's book often works over an algebraically closed field, and Qing Liu doesn't, and Lui's book has a longer treatment of blow ups, and lots of good stuff about models of curves); Silverman's AEC II (especially the chapters on models of curves) were very useful too.

Then I got crazy and read about 70% of EGA. Ravi Vakil and others had a "seminar of pain"; we liked the idea and had our own (and even convinced the Clay institute to fund us). The summer before, to prepare, I would wake up and spend about the first 3 hours of each day reading through EGA. (This is surely overkill.) 

In modern times, one should read Ravi Vakil's book "Foundations of Algebraic Geometry" (and really work through a lot of it, taking a calendar year or more) instead of Harthshorne, backtracking to Atiyah--Macdonald and Eisenbud's commutative algebra books when necessary (though, if you have time, working through Atiyah--Macdonald is a good warm up for Vakil), reading the Eisenbud--Harris "the geometry of schemes", and finding other random things to read to supplement this (again, I really like Silverman's AEC). 

For motivation, the best answer is that there isn't really a good way to do geometry over finite fields, or Z (or to understand how geometry changes in families, or how geometry is preserved, or changes, when reducing modulo a prime, or understanding singularities) without schemes. (Ditto with sheaves and cohomology, there is a long list of things that are insane to work with without those.) 

The first really striking example from Hartshorne's class is intersecting a line with a circle. Most of the time you get 2 distinct points, but if the line is tangent you only get one point. But actually, if you work with the scheme theoretic intersection, the "one point" is really a "singular double point" and the scheme structure truthfully and meaningfully keeps track of the fact that the point arose as a limit of two points. In fact, there are whole sub-sub fields which study, basically, the geometry of "0 dimensional" schemes (this leads you to study Hilbert schemes). So in geometry, points can be "big" or "small", and can break apart kind of like atoms. Also, making sense of something like a tangent line to a curve over F_p is just a lot cleaner with "algebraic" diffrentials and so on.





