#+TITLE: My experience learning Mazur's Torsion and Isogeny theorems
#+BIND: org-export-html-auto-postamble nil
#+ATTR_HTML: border="2" rules="all" frame="border" align="center"
#+OPTIONS: toc:nil 
#+OPTIONS: author:nil 
#+OPTIONS: html-postamble:nil
#+OPTIONS: num:nil 
#+OPTIONS: \n
#+OPTIONS: *
#+OPTIONS: toc:nil        (no TOC at all)
#+options: num:nil
#+OPTIONS:   H:2 





I spent about 2-3 months in the summer of 2008 (after my 4th year of graduate school). At that point I was able to read and understand everything (with a lot of work). I had some external motivation to read it: I had posted my first paper to the arxiv (here https://arxiv.org/abs/0803.0973v1); Matt Baker noticed it in the daily posting and wrote to me and suggested that it seemed ike Momose's papers about X_sp were in some sense doing "bad reduction Chabauty", and that it would be worthwhile for me to read those papers and see if I could prove anything new. Reading those papers also mean reading Mazur's papers first. Near the end of that summer, Bilu--Parent--Rebolledo started posting papers like this https://arxiv.org/abs/0807.4954 which completely solved the problem I was working on (and was published in Annals), so I switched gears (but was happy to have put in the work to read Mazur's papers). 

Anyway, here's my path before that. 

As an undergrad, I read Silverman and Tate's book about Elliptic curves, then Koblitz. Then I read this survey by Rubin and Silverberg

https://www.ams.org/journals/bull/2002-39-04/S0273-0979-02-00952-7/S0273-0979-02-00952-7.pdf

and, about Mazur's theorem, thought "what a simple statement, I wonder what the proof is like". I printed out the paper (this was 2003), not realizing that it was 100+ pages. I didn't get very far. 

In grad school, I spent the first year working through Hartshorne, Neurkirch, and Silverman's AEC (+ some sporadic other reading). Some of the older students like Jared Weinstein or Soroosh Yazdani, who had recently led a reading course working through the proof, explained a lot of the details to me, but I still didn't know enough about modular curves to make any real progress. 

My second year I started working on research problems. I spent a long time digesting "Twists of X(7) and primitive solutions to x^2 + y^3 = z^7" by Poonen--Schaefer--Stoll, and trying to generalize to 2-3-11. (I eventually generalized to 2-3-10...) This required really learning about modular curves, modular forms, level lowering, and so on. A lot of this I learned by Poonen explaining things to me in our weekly meetings. I did read through all of Milne's notes on modular curves, and lots of course notes by William Stein, the survey article by Tom Weston, the first two chapters of the Cornel--Silverman, the survey by Diamond and Im, and read lots of bits and pieces of Diamond and Sherman. 

The best thing to happen, though, was the following. I participated in the 2006 Clay summer school on Arithmetic Geometry (in Gottingen). It was fantastic. There were numerous "short courses", sometimes just one or two lectures, many week long, and Darmon gave a 2 week course explaining the proofs of Fermat's Last Theorem, Mazur's Theorem, and the Mordell Conjecture. Obviously he didn't cover every detail; but he explained many of the main ideas of the proofs, and still gave lots of detail. There are now some notes from his lectures

"Rational points on curves" Proceedings of the Clay Summer School on the arithmetic of curves, surfaces, and higher-dimensional varieties

that I still frequently refer to. (Rebolledo also wrote some excellent notes on the proof of Merel's theorem, which clarified a lot for me). I should also say that I guess I didn't read Mazur's full paper; there are many parts that are much simpler now (e.g., Kolyvagyn's theorem was not known at the time). I spent a lot of time that summer asking people to explain details to me. I didn't try to read the paper then though.


Brian Conrad also ran a Mazur's method learning seminar at Michigan 

http://math.stanford.edu/~conrad/vigregroup/vigre03.html

with several good notes. Honestly, it is possible to meaningfully learn lots of bits of the proof rigorously without too much background (e.g., "ruling out small primes" from his link) and get a good overview of the components of the proof. Assuming you already know about modular curves, and BSD, and modular abelian varieties etc, one could give a fairly faithful outline of the proof in half an hour. If you get anxious about technical stuff like "is the analytification of a modular curve the "analytic" modular curve?", then Conrad has you covered too (he taught a course here http://virtualmath1.stanford.edu/~conrad/248BPage/handouts.html which has several good handouts).


The next year I began working more with Chabauty's method, and wrote a paper (that had an error!) about Chabauty in the bad reduction case. See above re: comments from Matt Baker. I also noticed that Chabauty was related to Mazur's method, though Mazur never mentions Chabauty (and Matt Baker even has a paper making this explicit). I gave some talks at our student seminar about modular curves too (e.g., stuff like how you can see the primes of good reduction from the moduli problem + infinitesimal criterion for smoothness). 

So I was always learning bits and pieces before I finally sat down to read the paper. Basically I spent 3 hours each morning for about 2 months, and by that point I had most (but definitely not all) of the background I needed.

Last summer (2020), I was finishing up my (joint) Sporadic Cubic Torsion paper and ended up rereading lots of (parts of) Mazur's papers. There is a lot that I certainly didn't get the significance of during my first read and I learned a lot that is still useful. 
